Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),
    path('products/',include('products.urls')),
]



































urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('add/<slug:slug>/',views.cart_add , name='cart_add'),
    path('cart_detail',views.cart_detail , name='cart_detail'),
    path('item_clear/<slug:slug>/',views.item_clear , name='item_clear'),
    path('item_increment/<slug:slug>/',views.item_increment , name='item_increment'),
    path('item_decrement/<slug:slug>/',views.item_decrement , name='item_decrement'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
	path('confrm_checkout/',views.confrm_checkout , name='confrm_checkout'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<slug:slug>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),
]

products/urls.py
from django.urls import path
from . import views



app_name = 'products'

urlpatterns = [
    path('sell/',views.sell,name="sell")
]

users/urls.py
from django.urls import path
from . import views



app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout , name='logout'),
    path('dashboard/', views.dashboard , name='dashboard'),
    path('<int:user_id>/profile/', views.profile , name='profile'),
    # path('myposts/', views.myposts , name='myposts'),
]

wishlists/urls.py
from django.urls import path
from . import views



app_name = 'wishlists'

urlpatterns = [
    path('<int:product_id>/add/', views.add_wishlist , name='add_wishlist'),
    path('my_wishlists/', views.my_wishlists , name='my_wishlists'),
    path('clear_wishlists/', views.clear_wishlists , name='clear_wishlists'),
    path('<int:wishlist_id>/delete_wishlist/', views.delete_wishlist , name='delete_wishlist'),
    # path('<int:post_id>/delete/', views.delete_wishlist , name='delete_wishlist'),


]

templates/partials/_footer.html
<footer class="footer bg-dark" style="left: 0;">
  <div class="container text-center d-flex justify-content-between">
    <span class="text-muted">Created By: Tushar Talesara & Vaibhav Khater</span>
    <a href="{% url 'products:sell' %}" class="text-muted">Sell With Us</a>
  </div>
</footer>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'pages:home' %}">SwapKart</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pages:about' %}">About</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'pages:all_products' %}" class="nav-link">All Products</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">Categories</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for cat in categories %}
          {console.log('hello')}
          <a class="dropdown-item" href="{% url 'pages:category_by_slug' cat.slug %}">{{cat.title}}</a>
          {% endfor %}
        </div>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right mr-5">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:dashboard' %}">DashBoard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:profile' user.id %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wishlists:my_wishlists' %}">My WishLists</a>
      </li>
      <li class="nav-item mr-3">
        <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">
          <i class="fas fa-sign-out-alt"></i> Logout
        </a>

        <form method="post" id="logout" action="{% url 'users:logout' %}">
          {% csrf_token %}
          <input type="hidden">
        </form>
      </li>
      <li class="nav-item">
        <a href="{% url 'cart:cart_detail' %}" class="nav-link">
          <i class="fa fa-cart-plus" style="font-size:30px" aria-hidden="true"></i>
          <strong class="text-info">({{request.session.cart | length}}) Item</strong>
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
      </li>
      {% endif %}


    </ul>

  </div>
</nav>