Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),
    path('products/',include('products.urls')),
]



































urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('add/<slug:slug>/',views.cart_add , name='cart_add'),
    path('cart_detail',views.cart_detail , name='cart_detail'),
    path('item_clear/<slug:slug>/',views.item_clear , name='item_clear'),
    path('item_increment/<slug:slug>/',views.item_increment , name='item_increment'),
    path('item_decrement/<slug:slug>/',views.item_decrement , name='item_decrement'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
	path('confrm_checkout/',views.confrm_checkout , name='confrm_checkout'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<slug:slug>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),
]

wishlists/urls.py
from django.urls import path
from . import views



app_name = 'wishlists'

urlpatterns = [
    path('<int:product_id>/add/', views.add_wishlist , name='add_wishlist'),
    path('my_wishlists/', views.my_wishlists , name='my_wishlists'),
    path('clear_wishlists/', views.clear_wishlists , name='clear_wishlists'),
    path('<int:wishlist_id>/delete_wishlist/', views.delete_wishlist , name='delete_wishlist'),
    # path('<int:post_id>/delete/', views.delete_wishlist , name='delete_wishlist'),


]

wishlists/models.py
from django.db import models
from datetime import datetime


from products.models import Product
from django.contrib.auth.models import User
# Create your models here.


class WishList(models.Model):
	user_id = models.IntegerField()
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='wishlist_product')
	
	# def __str__(self):
	# 	return str(self.product.id)

wishlists/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required

from products.models import Product
from categories.models import Category
from wishlists.models import WishList


@login_required(login_url="/users/login")
def add_wishlist(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    user_id = request.user.id
    wl = WishList(user_id=user_id, product=product)
    wl.save()
    if wl:
        messages.success(request, 'Item added to your wishlist')
        return redirect('/')
    else:
        messages.warning(request, 'SomeThing Went Wrong')
        return redirect('/')

@login_required(login_url="/users/login")
def my_wishlists(request):
    products = WishList.objects.filter(user_id=request.user.id)
    wishlists = []
    categories = Category.objects.all()
    for i in products:
        pro = str(i.product)
        product = Product.objects.get(title=pro)
        wishlists.append({
            "photo": product.photo.url,
            "title": product.title,
            "summary": product.summary,
            "slug": product.slug,
            "id": i.pk
        })
    context = {
        'title': 'My WishList',
        'wishlists': wishlists,
        'categories': categories,
        # 'id':id
    }
    return render(request, 'wishlists/all_wishlists.html', context)


@login_required(login_url="/users/login")
def clear_wishlists(request):
    context = {
        'title': 'My WishList',
    }
    return render(request, 'wishlists/all_wishlists.html', context)


@login_required(login_url="/users/login")
def delete_wishlist(request, wishlist_id):
    wl = WishList.objects.get(pk=wishlist_id)
    wl.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

templates/wishlists/all_wishlists.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}



{% block content %}

<div class="col-md-3">
	<ul class="list-group">
		<li class="list-group-item disabled">Categories</li>
		{% for cat in categories %}
		<li class="list-group-item"><a href="{% url 'pages:category_by_slug' cat.slug %}">{{cat.title}}</a></li>
		{% endfor %}
	</ul>
</div>

<div class="col-md-8 mt-3">
	<a href="{% url 'wishlists:clear_wishlists' %}" class="btn btn-danger btn-block">Clear wishlists</a><br>
	{% for value in wishlists %}
	<div class="card card-block text-{1:center|right} mt-3">
		<img class="rounded mx-auto d-block" src="{{value.photo}}" width="150px" alt="">
		<h4 class="card-title text-center">{{value.title}}</h4>
		<p class="card-text text-center">{{value.summary}}</p>
	</div>
	<div class="clearfix">
		<a href="{% url 'pages:product_by_slug' value.slug %}" class="btn btn-primary btn-xs float-left">Read More</a>

		<a href="{% url 'wishlists:delete_wishlist' value.id %}"
			class="btn btn-primary btn-xs float-right">Delete</a><br>
	</div>
	{% endfor %}
</div>
{% endblock content %}