Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),
    path('products/',include('products.urls')),
]



































urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('add/<slug:slug>/',views.cart_add , name='cart_add'),
    path('cart_detail',views.cart_detail , name='cart_detail'),
    path('item_clear/<slug:slug>/',views.item_clear , name='item_clear'),
    path('item_increment/<slug:slug>/',views.item_increment , name='item_increment'),
    path('item_decrement/<slug:slug>/',views.item_decrement , name='item_decrement'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
	path('confrm_checkout/',views.confrm_checkout , name='confrm_checkout'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<slug:slug>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),
]

wishlists/urls.py
from django.urls import path
from . import views



app_name = 'wishlists'

urlpatterns = [
    path('<int:product_id>/add/', views.add_wishlist , name='add_wishlist'),
    path('my_wishlists/', views.my_wishlists , name='my_wishlists'),
    path('clear_wishlists/', views.clear_wishlists , name='clear_wishlists'),
    path('<int:wishlist_id>/delete_wishlist/', views.delete_wishlist , name='delete_wishlist'),
    # path('<int:post_id>/delete/', views.delete_wishlist , name='delete_wishlist'),


]

templates/ecom/about.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}



{% block content %}
<div class="container-fluid" style="background: url('https://img.freepik.com/premium-photo/website-internet-contact-us-page-concept-with-phone-email-mail-icons-hotline-support-contact-communication-concept-wide-panorama-view-sign-mail-mobile-phone-icons-copy-space_256259-1518.jpg?w=2000'); background-position: center;	background-repeat: no-repeat; background-size: cover; height: 100vh; text-align: center; align-items: center; display: flex; justify-content: center; font-size: 50px; color: rgb(103, 95, 95);">
	<!-- <div class="container" style= height: 100;"> -->
		<!-- <p> -->
			Ecommerce website created using Django and using mySQL database as project for ITW2
		<!-- </p> -->
	<!-- </div> -->
</div>
{% endblock content %}

templates/ecom/all_products.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}



{% block content %}

{% for p in products %}
<div class="col-md-4 mt-4">
  <div class="card-deck-wrapper">
    <div class="card-deck">
      <div class="card">
        <a href="{% url 'pages:product_by_slug' p.slug %}" class="float-right">
          <img class="card-img-top" height="350px" src="{{p.photo.url}}" alt="Card image cap">
        </a>
        
        <div class="card-block">
          <h4 class="card-title text-center text-secondary mt-2">
            <a href="{% url 'pages:product_by_slug' p.slug %}" class="list-group-item-action">
              {{p.title}}
            </a>
          </h4>

          <p class="card-text text-center lead">
            {{p.summary}}<br>
            <strong>Category: </strong><a href="{% url 'pages:category_by_slug' p.category.slug %}">{{p.category.title}}</a><br>   
            <a href="{% url 'wishlists:add_wishlist' p.id %}">Add To Wish List</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}


<div class="mx-auto mt-4 clearfix">

  {% if products.has_other_pages %}

  <ul class="pagination">
    {% if products.has_previous %}
    <li class="page-item">
      <a href="?page={{products.previous_page_number}}" class="page-link">&laquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">&laquo;</a>
    </li>
    {% endif %}
    {% for i in products.paginator.page_range %}
    {% if products.number == i %}

    <li class="page-item active">
      <a class="page-link">{{i}}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a href="?page={{i}}" class="page-link">{{i}}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if products.has_next %}
    <li class="page-item">
      <a href="?page={{products.next_page_number}}" class="page-link">&raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">&raquo;</a>
    </li>
    {% endif %}
  </ul>

  {% else %}

  {% endif %}

</div>



{% endblock content %}

templates/ecom/index.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}



{% block content %}
<div class="container-fluid">
	<div class="row">
		{% for p in products %}
		<!-- <div class="col-md-6 mt-5"> -->
			<div class="card-deck" style="width: 23%; margin: 25px 14px 25px 14px;">
				<div class="card">
					<img class="card-img-top" height="300px" src="{{p.photo.url}}" alt="Card image cap">
					<div class="card-body">
						<h4 class="card-title text-center text-secondary mt-2">
							<a href="{% url 'pages:product_by_slug' p.slug %}" class="list-group-item-action">
								{{p.title}}
							</a>
						</h4>
						<p class="card-text text-center lead">
							{{p.summary}}<br>
							<strong>Category: </strong><a
								href="{% url 'pages:category_by_slug' p.category.slug %}">{{p.category.title}}</a><br>
							<a href="{% url 'wishlists:add_wishlist' p.id %}">Add To Wish List</a>
						</p>
					</div>
				</div>
			</div>
		<!-- </div> -->
		{% endfor %}
	</div>
</div>











{% endblock content %}

templates/ecom/show.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}



{% block content %}

<!-- <div class="col-md-4 mt-4">
  <ul class="list-group">
    <li class="list-group-item"><a href="{% url 'pages:all_products' %}">All Products</a></li>
  </ul>
</div> -->
<div class="d-flex">
  <div class="col-md-8 mt-4">
    <img src="{{product.photo.url}}" width="400px" class="img-thumbnail" alt="">
  </div>
  <div class="col-md-10 mt-4">
    <h1 class="page-header">{{product.title}}</h1>
    <br>
    <p>{{product.description}}</p>
    <p>Price : Rs. {{product.price}}</p>
    <p>Avaiable : {{product.quantity}}</p>
    <p><a href="{% url 'cart:cart_add' product.slug %}">Add to cart</a></p>
  </div>
</div>
{% endblock content %}